### ISSUE TITLE
Simplification of '\f -> f grid'

### ISSUE THREAD

**Issue by frerich** [NeilNjae/advent-of-code-17#1]
Hi,

not sure an 'issue' is the best way to send this comment, but I just looked at your Haskell code (good stuff) and noticed that on [day 21](https://github.com/NeilNjae/advent-of-code-17/blob/master/src/advent21/advent21.hs#L71) you used

```haskell
    map (\f -> f grid) ...
```

You might enjoy expressing this as

```haskell
    map ($ grid) ...
```

I think this is one of the lesser-known uses of `$`. :-)

**Comment by NeilNjae** [comment]
That's really neat! Obvious when it's pointed out. Thanks very much for taking the time to comment.
